<?php

namespace ContainerLWDX5TN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PB9oH_GService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pB9oH.g' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pB9oH.g'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'produit' => ['privates', '.errored..service_locator.pB9oH.g.App\\Entity\\Produit', NULL, 'Cannot autowire service ".service_locator.pB9oH.g": it references class "App\\Entity\\Produit" but no such service exists.'],
            'produitRepository' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
        ], [
            'entityManager' => '?',
            'produit' => 'App\\Entity\\Produit',
            'produitRepository' => 'App\\Repository\\ProduitRepository',
        ]);
    }
}
