<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFxNjWUM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFxNjWUM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFxNjWUM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFxNjWUM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFxNjWUM\App_KernelDevDebugContainer([
    'container.build_hash' => 'FxNjWUM',
    'container.build_id' => '6894183f',
    'container.build_time' => 1692539816,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFxNjWUM');
