<?php

namespace ContainerFxNjWUM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Hx9tlLOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Hx9tlLO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Hx9tlLO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'coach' => ['privates', '.errored..service_locator.Hx9tlLO.App\\Entity\\Coach', NULL, 'Cannot autowire service ".service_locator.Hx9tlLO": it references class "App\\Entity\\Coach" but no such service exists.'],
            'coachRepository' => ['privates', 'App\\Repository\\CoachRepository', 'getCoachRepositoryService', true],
        ], [
            'coach' => 'App\\Entity\\Coach',
            'coachRepository' => 'App\\Repository\\CoachRepository',
        ]);
    }
}
