<?php

namespace ContainerFxNjWUM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QSOG90SService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qSOG90S' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qSOG90S'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CoachController::delete' => ['privates', '.service_locator.Hx9tlLO', 'get_ServiceLocator_Hx9tlLOService', true],
            'App\\Controller\\CoachController::edit' => ['privates', '.service_locator.Hx9tlLO', 'get_ServiceLocator_Hx9tlLOService', true],
            'App\\Controller\\CoachController::index' => ['privates', '.service_locator.SAYXif1', 'get_ServiceLocator_SAYXif1Service', true],
            'App\\Controller\\CoachController::new' => ['privates', '.service_locator.RNsiPAw', 'get_ServiceLocator_RNsiPAwService', true],
            'App\\Controller\\CoachController::show' => ['privates', '.service_locator.Veo9UrM', 'get_ServiceLocator_Veo9UrMService', true],
            'App\\Controller\\ProduitController::delete' => ['privates', '.service_locator.bn70ThF', 'get_ServiceLocator_Bn70ThFService', true],
            'App\\Controller\\ProduitController::edit' => ['privates', '.service_locator.pB9oH.g', 'get_ServiceLocator_PB9oH_GService', true],
            'App\\Controller\\ProduitController::index' => ['privates', '.service_locator.GwDgJIn', 'get_ServiceLocator_GwDgJInService', true],
            'App\\Controller\\ProduitController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ProduitController::show' => ['privates', '.service_locator.iGUm1r8', 'get_ServiceLocator_IGUm1r8Service', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.iQAD6w2', 'get_ServiceLocator_IQAD6w2Service', true],
            'App\\Controller\\RegistrationController::registerAdmin' => ['privates', '.service_locator.iQAD6w2', 'get_ServiceLocator_IQAD6w2Service', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.pXhSQsU', 'get_ServiceLocator_PXhSQsUService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.kdKsWx5', 'get_ServiceLocator_KdKsWx5Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.9uW928t', 'get_ServiceLocator_9uW928tService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.jYO2.AM', 'get_ServiceLocator_JYO2_AMService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.Zhsi5nT', 'get_ServiceLocator_Zhsi5nTService', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\CoachController:delete' => ['privates', '.service_locator.Hx9tlLO', 'get_ServiceLocator_Hx9tlLOService', true],
            'App\\Controller\\CoachController:edit' => ['privates', '.service_locator.Hx9tlLO', 'get_ServiceLocator_Hx9tlLOService', true],
            'App\\Controller\\CoachController:index' => ['privates', '.service_locator.SAYXif1', 'get_ServiceLocator_SAYXif1Service', true],
            'App\\Controller\\CoachController:new' => ['privates', '.service_locator.RNsiPAw', 'get_ServiceLocator_RNsiPAwService', true],
            'App\\Controller\\CoachController:show' => ['privates', '.service_locator.Veo9UrM', 'get_ServiceLocator_Veo9UrMService', true],
            'App\\Controller\\ProduitController:delete' => ['privates', '.service_locator.bn70ThF', 'get_ServiceLocator_Bn70ThFService', true],
            'App\\Controller\\ProduitController:edit' => ['privates', '.service_locator.pB9oH.g', 'get_ServiceLocator_PB9oH_GService', true],
            'App\\Controller\\ProduitController:index' => ['privates', '.service_locator.GwDgJIn', 'get_ServiceLocator_GwDgJInService', true],
            'App\\Controller\\ProduitController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ProduitController:show' => ['privates', '.service_locator.iGUm1r8', 'get_ServiceLocator_IGUm1r8Service', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.iQAD6w2', 'get_ServiceLocator_IQAD6w2Service', true],
            'App\\Controller\\RegistrationController:registerAdmin' => ['privates', '.service_locator.iQAD6w2', 'get_ServiceLocator_IQAD6w2Service', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.pXhSQsU', 'get_ServiceLocator_PXhSQsUService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.kdKsWx5', 'get_ServiceLocator_KdKsWx5Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.9uW928t', 'get_ServiceLocator_9uW928tService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.jYO2.AM', 'get_ServiceLocator_JYO2_AMService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.Zhsi5nT', 'get_ServiceLocator_Zhsi5nTService', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\CoachController::delete' => '?',
            'App\\Controller\\CoachController::edit' => '?',
            'App\\Controller\\CoachController::index' => '?',
            'App\\Controller\\CoachController::new' => '?',
            'App\\Controller\\CoachController::show' => '?',
            'App\\Controller\\ProduitController::delete' => '?',
            'App\\Controller\\ProduitController::edit' => '?',
            'App\\Controller\\ProduitController::index' => '?',
            'App\\Controller\\ProduitController::new' => '?',
            'App\\Controller\\ProduitController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::registerAdmin' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CoachController:delete' => '?',
            'App\\Controller\\CoachController:edit' => '?',
            'App\\Controller\\CoachController:index' => '?',
            'App\\Controller\\CoachController:new' => '?',
            'App\\Controller\\CoachController:show' => '?',
            'App\\Controller\\ProduitController:delete' => '?',
            'App\\Controller\\ProduitController:edit' => '?',
            'App\\Controller\\ProduitController:index' => '?',
            'App\\Controller\\ProduitController:new' => '?',
            'App\\Controller\\ProduitController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:registerAdmin' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'App\\Controller\\UserController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
